config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  #get 'pages/home'

  get 'about', to: 'pages#about'
  #get 'pages/contact'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, allow_destroy: true, reject_if: lambda {|attr| attr['name'].blank?}

  include Placeholder
  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  #def self.angular
  #  where(subtitle: "Angular")
  #end

  #scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails") }

  def self.by_position
    order("position ASC")
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :edit, :update, :sort]}, site_admin: :all
  layout "portfolio"

  def index
    @portfolio_items = Portfolio.by_position
    #@portfolio_items = Portfolio.where(subtitle: "Angular")
    #@portfolio_items = Portfolio.angular
    #@portfolio_items = Portfolio.ruby_on_rails_portfolio_items
  end

  def angular
    #@portfolio_items = Portfolio.all
    @angular_portfolio_items = Portfolio.where(subtitle: "Angular")
    #@portfolio_items = Portfolio.angular
    #@portfolio_items = Portfolio.ruby_on_rails_portfolio_items
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    head :ok
  end

  def new
    @portfolio_item = Portfolio.new
    # 3.times {@portfolio_item.technologies.build}
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
        #format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        #format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
        #format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        #format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Potfolio was successfully destroyed.' }
    end
  end

  private
    def portfolio_params
      params.require(:portfolio).permit(
        :title,
        :subtitle,
        :body,
        :thumb_image,
        :main_image,
        technologies_attributes: [:id, :name, :_destroy]
      )
    end

    def set_portfolio_item
      @portfolio_item= Portfolio.find(params[:id])
    end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img img, type
    # if img.model.main_image? || img.model.thumb_image?
    if img
      img
    elsif type == 'thumb'
      image_generator(height:'350', width:'200')
    else
      image_generator(height:'600', width:'400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: "form-control" %>
      </div>

      <div class="form-group">
        <!--  <%= form.label :main_image %>  -->
        <label class="btn btn-primary">
          Upload a main image file <%= form.file_field :main_image, class: "form-control", style: 'display:none' %>
        </label>
      </div>

      <div class="form-group">
        <!--  <%= form.label :thumb_image %>  -->
        <label class="btn btn-primary">
          Upload a thumb image file <%= form.file_field :thumb_image, class: "form-control", style: 'display:none' %>
        </label>
      </div>

    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: "form-control", rows: 12 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-md-12">
      <h2>Technologies Used</h2>
      <div>
      <%= form.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>
      <div><%= link_to_add_association 'Add Technology', form, :technologies %></div>
</div>
      <div class="form-group">
        <%= form.submit "Submit", class: "btn btn-primary btn-block" %>
      </div>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<!---<h2><%= portfolio_item.title %></h2>--->

<!-- <p><%= link_to "Edit", edit_portfolio_path(portfolio_item.id) if logged_in?(:site_admin) %></p>
<p><%= link_to 'Destroy', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %></p> -->
<!---<a href="/portfolios/<%=portfolio_item.id%>/edit">Edit</a>--->
<!-- <ul>
  <li></li>
  <li><%= portfolio_item.body %></li>
  -Negative if could be replaced by unless-
  <li></li>
</ul> -->

<div class="card" data-id="<%=portfolio_item.id%>">

  <%= image_tag portfolio_img(portfolio_item.thumb_image.url, 'thumb'), width: "100%", height: "200px"%>
  <h4><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></h4>
  <p class="card-text"><%= portfolio_item.subtitle %></p>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  Technology <%= (f.label :name)%>
  <%= f.text_field :name, class: "form-control" %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<p><%= link_to "Add", new_portfolio_path if logged_in?(:site_admin) %></p>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <!---<h2><%= portfolio_item.title %></h2>--->
  <h2><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></h2>
  <p><%= link_to "Edit", edit_portfolio_path(portfolio_item.id) if logged_in?(:site_admin) %></p>
  <p><%= link_to 'Destroy', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %></p>
  <!---<a href="/portfolios/<%=portfolio_item.id%>/edit">Edit</a>--->
  <ul>
    <li><%= portfolio_item.subtitle %></li>
    <li><%= portfolio_item.body %></li>
    <!---Negative if could be replaced by unless--->
    <li><%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %></li>
  </ul>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container mt-4 mb-4">
  <h1>Edit this Portfolio item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">

      <!-- <p><%= link_to "Add", new_portfolio_path if logged_in?(:site_admin) %></p> -->

      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container mt-4 mb-4">
  <h1>Create a new Portfolio item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container mt-4">
  <div class="mb-4 row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio_item.main_image.url, 'main'), width: "100%"%>

    </div>

    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>

<hr>

      <h4><%= @portfolio_item.subtitle %></h4>




      <p><%= @portfolio_item.body %></p>

      <hr>

      <h3>Technologies Used:</h3>
      <% @portfolio_item.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>

      <hr>

      <p>
        <%= link_to "View other items", portfolios_path %>
        <%= link_to "Edit", edit_portfolio_path(@portfolio_item) if logged_in?(:site_admin) %>
        <%= link_to 'Destroy', portfolio_path(@portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
      </p>

    </div>
  </div>
</div>