config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  #get 'pages/home'

  get 'about', to: 'pages#about'
  #get 'pages/contact'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>

  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">I. Bonaldi</h3>
    <nav class="nav nav-masthead"><!--
      <%= link_to "Home", root_path, class: "nav-link"  %>
      <%= link_to "About", about_path, class: "nav-link"  %>
      <%= link_to "Contact", contact_path, class: "nav-link" %>
      <%= link_to "Blogs", blogs_path, class: "nav-link" %>
      <%= link_to "Portfolios", portfolios_path, class: "nav-link" %>
      -->
      <%= nav_helper "nav-link ml-4", "span"%>
      <%= login_helper "nav-link ml-4"%>
     </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p> <%= copyright_generator %> </p>
  <p>
    <a href="#" class="text-white">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">I.Bonaldi's Blog</h1>
    <p class="lead blog-description">I already know a lot about it. And I'm learning it ALL again in another language, with another framework. And still looks fun.</p>
    <%= link_to 'New Blog', new_blog_path if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav"><!--
      <%= link_to "Home", root_path, class: "nav-link"  %>
      <%= link_to "About", about_path, class: "nav-link"  %>
      <%= link_to "Contact", contact_path, class: "nav-link" %>
      <%= link_to "Blogs", blogs_path, class: "nav-link" %>
      <%= link_to "Portfolios", portfolios_path, class: "nav-link" %> -->

      <%= nav_helper "nav-link", "span"%>
      <%= login_helper "nav-link"%>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>
  <!-- <div class="sidebar-module">
    <h4>Archives</h4>
    <ol class="list-unstyled">
      <li><a href="#">March 2014</a></li>
      <li><a href="#">February 2014</a></li>
      <li><a href="#">January 2014</a></li>
      <li><a href="#">December 2013</a></li>
      <li><a href="#">November 2013</a></li>
      <li><a href="#">October 2013</a></li>
      <li><a href="#">September 2013</a></li>
      <li><a href="#">August 2013</a></li>
      <li><a href="#">July 2013</a></li>
      <li><a href="#">June 2013</a></li>
      <li><a href="#">May 2013</a></li>
      <li><a href="#">April 2013</a></li>
    </ol>
  </div> -->
  <div class="sidebar-module">
    <h4>Find us!</h4>
    <!-- <ol class="list-unstyled">
      <li class="mb-3"> --><a class="mr-2" href="#"><%= fa_icon "github 2x"%></a><!-- </li>
      <li class="mb-3"> --><a class="mr-2" href="#"><%= fa_icon "facebook 2x"%></a><!-- </li>
      <li> --><a class="mr-2" href="#"><%= fa_icon "twitter 2x"%></a><!-- </li>
    </ol> -->
    <a class="mr-2" href="#"><%= fa_icon "bus 2x"%></a>
    <a href="#"><%= fa_icon "instagram 2x"%></a>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%=location%>">
  <%= link_to "Home", root_path %>
  <span>.</span>
  <%= link_to "About", about_path %>
  <span>.</span>
  <%= link_to "Contact", contact_path %>
  <span>.</span>
  <%= link_to "Blogs", blogs_path %>
  <span>.</span>
  <%= link_to "Portfolios", portfolios_path %>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted bg-dark">
  <div class="container text-white">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Album example</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <%= link_to 'About me', about_path, class: 'btn btn-primary' %>
      <%= link_to 'Meet my blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Site map</h4>
        <ul class="list-unstyled">
          <!-- <li><%= link_to "Home", root_path, class: "text-white"  %></li>
          <li><%= link_to "About", about_path, class: "text-white"  %></li>
          <li><%= link_to "Contact", contact_path, class: "text-white" %></li>
          <li><%= link_to "Blogs", blogs_path, class: "text-white" %></li> -->

          <%= nav_helper "text-white", "li"%>
          <li><%= link_to "Portfolios", portfolios_path, class: "text-white" %></li>
          <li><%= login_helper "text-white"%></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-dark bg-dark">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">I. Bonaldi's Portfolio</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>